apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: default
  labels:
    app: user
spec:
  selector:
    matchLabels:
      app: user
  #replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user-container
        image: 599270912675.dkr.ecr.us-east-1.amazonaws.com/user:v1.0
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shift
  namespace: default
  labels:
    app: shift
spec:
  selector:
    matchLabels:
      app: shift
  #replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: shift
    spec:
      containers:
      - name: shift-container
        image: 599270912675.dkr.ecr.us-east-1.amazonaws.com/shift:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: user-service
  labels:
    app: user
spec:
  type: LoadBalancer
  selector:
    app: user
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: shift-service
  labels:
    app: shift
spec:
  type: LoadBalancer
  selector:
    app: shift
  ports:
    - port: 80
      targetPort: 80